# Generated by Django 4.1.3 on 2024-02-08 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedHeroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('attribute', models.CharField(max_length=155)),
                ('portraiturl', models.CharField(max_length=155)),
                ('iconurl', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('banned', models.ManyToManyField(through='dotaapi.BannedHeroes', to='dotaapi.hero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bannedheroes',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotaapi.hero'),
        ),
        migrations.AddField(
            model_name='bannedheroes',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotaapi.profile'),
        ),
    ]
